// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Start a new agent session.
	 * 
	 *  Returns the session UUID on success. Events stream to `channel` via the
	 *  16ms flush task. Cancel via `stop_session(session_id)`.
	 */
	startSession: (prompt: string, persona: string, channel: Channel<IpcAgentEvent>) => typedError<string, string>(__TAURI_INVOKE("start_session", { prompt, persona, channel })),
	// Cancel an active session.
	stopSession: (sessionId: string) => typedError<null, string>(__TAURI_INVOKE("stop_session", { sessionId })),
	// Query whether a session is still running.
	getSessionStatus: (sessionId: string) => typedError<SessionStatus, string>(__TAURI_INVOKE("get_session_status", { sessionId })),
};

/* Types */
/**
 *  IPC-safe mirror of `AgentEvent`. All fields are JSON-serializable.
 *  `Clone` is safe — no non-Clone types here (unlike `AgentEvent`).
 */
export type IpcAgentEvent = { type: "TextDelta"; data: {
	content: string,
} } | { type: "ToolCallStart"; data: {
	id: string,
	name: string,
} } | { type: "ToolCallDelta"; data: {
	id: string,
	arguments_delta: string,
} } | { type: "ToolCallComplete"; data: {
	id: string,
	name: string,
	arguments: "Null" | ({ Bool: boolean }) & { Array?: never; Number?: never; Object?: never; String?: never } | ({ Number: ({ f64: number }) & { i64?: never; u64?: never } | ({ i64: number }) & { f64?: never; u64?: never } | ({ u64: number }) & { f64?: never; i64?: never } }) & { Array?: never; Bool?: never; Object?: never; String?: never } | ({ String: string }) & { Array?: never; Bool?: never; Number?: never; Object?: never } | ({ Array: Value[] }) & { Bool?: never; Number?: never; Object?: never; String?: never } | ({ Object: { [key in string]: Value } }) & { Array?: never; Bool?: never; Number?: never; String?: never },
} } | { type: "ToolCallMalformed"; data: {
	id: string,
	raw: string,
	error: string,
} } | { type: "Usage"; data: {
	prompt_tokens: number,
	completion_tokens: number,
	cost_usd: number,
} } | { type: "Retry"; data: {
	attempt: number,
	delay_ms: number,
	reason: string,
} } | { type: "Error"; data: {
	message: string,
} } | { type: "ToolOutput"; data: {
	call_id: string,
	chunk: IpcToolOutputChunk,
} } | { type: "TaskComplete"; data: {
	call_id: string,
	verified: boolean,
	outcome: IpcVerificationOutcome,
} } | { type: "ImageRead"; data: {
	path: string,
	data_url: string,
} } | { type: "SandboxViolation"; data: {
	call_id: string,
	tool_name: string,
	resource: string,
	policy_rule: string,
	os_error: number | null,
} } | { type: "Paused" } | { type: "Aborted"; data: {
	reason: string,
} } | { type: "ContextTruncated"; data: {
	dropped_symbols: number,
	budget_tokens: number,
} } | { type: "IndexProgress"; data: {
	indexed: number,
	total: number,
} } | { type: "Verification"; data: {
	critic_role: string,
	verdict: string,
	reason: string,
	cost_usd: number,
} } | { type: "VerifierDisabled"; data: {
	reason: string,
	cost_usd: number,
} } | { type: "SessionSpawned"; data: {
	session_id: string,
	persona: string,
	created_at: number,
} } | { type: "SessionPaused"; data: {
	session_id: string,
	paused_at: number,
} } | { type: "SessionResumed"; data: {
	session_id: string,
	resumed_at: number,
} } | { type: "SessionForked"; data: {
	parent_id: string,
	child_id: string,
} } | { type: "ApprovalRequested"; data: {
	tool_name: string,
	command: string,
	sandbox_status: string,
} } | { type: "ApprovalDecision"; data: {
	tool_name: string,
	approved: boolean,
	decided_at: number,
} } | { type: "Unknown"; data: {
	event_type: string,
} };

// IPC-safe mirror of `ToolOutputChunk`.
export type IpcToolOutputChunk = ({ Stdout: string }) & { Closed?: never; Stderr?: never } | ({ Stderr: string }) & { Closed?: never; Stdout?: never } | ({ Closed: {
	exit_code: number | null,
	marker_detected: boolean,
} }) & { Stderr?: never; Stdout?: never };

// IPC-safe mirror of `VerificationOutcome`.
export type IpcVerificationOutcome = ({ Pending: {
	reason: string,
} }) & { Fail?: never; Pass?: never } | ({ Pass: {
	note: string,
} }) & { Fail?: never; Pending?: never } | ({ Fail: {
	reason: string,
} }) & { Pass?: never; Pending?: never };

// Session lifecycle status.
export type SessionStatus = "Running" | "Paused" | "Completed" | "Failed" | "Killed";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}


/** serde_json::Value — required by IpcAgentEvent.arguments */
export type Value = "Null" | { Bool: boolean } | { String: string } | { Number: number } | { Array: Value[] } | { Object: Record<string, Value> };
