// This file is generated by tauri-specta (tests/gen_bindings.rs).
// Run `cargo test -p kay-tauri --test gen_bindings` to regenerate.
// DO NOT edit manually.

import { invoke } from "@tauri-apps/api/core";
import { Channel } from "@tauri-apps/api/core";

// ── Types ────────────────────────────────────────────────────────────────────

export type IpcToolOutputChunk =
  | { Stdout: string }
  | { Stderr: string }
  | { Closed: { exit_code: number | null; marker_detected: boolean } };

export type IpcVerificationOutcome =
  | { Pending: { reason: string } }
  | { Pass: { note: string } }
  | { Fail: { reason: string } };

export type IpcAgentEvent =
  | { type: "TextDelta";         data: { content: string } }
  | { type: "ToolCallStart";     data: { id: string; name: string } }
  | { type: "ToolCallDelta";     data: { id: string; arguments_delta: string } }
  | { type: "ToolCallComplete";  data: { id: string; name: string; arguments: unknown } }
  | { type: "ToolCallMalformed"; data: { id: string; raw: string; error: string } }
  | { type: "Usage";             data: { prompt_tokens: number; completion_tokens: number; cost_usd: number } }
  | { type: "Retry";             data: { attempt: number; delay_ms: number; reason: string } }
  | { type: "Error";             data: { message: string } }
  | { type: "ToolOutput";        data: { call_id: string; chunk: IpcToolOutputChunk } }
  | { type: "TaskComplete";      data: { call_id: string; verified: boolean; outcome: IpcVerificationOutcome } }
  | { type: "ImageRead";         data: { path: string; data_url: string } }
  | { type: "SandboxViolation";  data: { call_id: string; tool_name: string; resource: string; policy_rule: string; os_error: number | null } }
  | { type: "Paused";            data: null }
  | { type: "Aborted";           data: { reason: string } }
  | { type: "ContextTruncated";  data: { dropped_symbols: number; budget_tokens: number } }
  | { type: "IndexProgress";     data: { indexed: number; total: number } }
  | { type: "Verification";      data: { critic_role: string; verdict: string; reason: string; cost_usd: number } }
  | { type: "VerifierDisabled";  data: { reason: string; cost_usd: number } }
  | { type: "Unknown";           data: { event_type: string } };

export type SessionStatus = "Running" | "Complete";

// ── Commands ─────────────────────────────────────────────────────────────────

export const commands = {
  async startSession(
    prompt: string,
    persona: string,
    channel: Channel<IpcAgentEvent>
  ): Promise<string> {
    return invoke<string>("start_session", { prompt, persona, channel });
  },

  async stopSession(sessionId: string): Promise<void> {
    return invoke<void>("stop_session", { sessionId });
  },

  async getSessionStatus(sessionId: string): Promise<SessionStatus> {
    return invoke<SessionStatus>("get_session_status", { sessionId });
  },
};
