//! Generates TypeScript bindings from tauri-specta.
//! Generates TypeScript bindings from tauri-specta.
//!
//! Run with:
//!   cargo test -p kay-tauri --test gen_bindings -- --nocapture
//!
//! The generated file is committed at `ui/src/bindings.ts`.
//! CI validates it is in sync via `scripts/check-bindings.sh`.

#[test]
fn export_tauri_bindings() {
    use std::io::Write;

    let bindings_path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("ui/src/bindings.ts");

    // Export via specta (clears + regenerates the file)
    tauri_specta::Builder::<tauri::Wry>::new()
        .commands(tauri_specta::collect_commands![
            kay_tauri::commands::start_session,
            kay_tauri::commands::stop_session,
            kay_tauri::commands::get_session_status,
        ])
        .export(
            specta_typescript::Typescript::default(),
            bindings_path.to_str().unwrap(),
        )
        .expect("export tauri-specta bindings");

    // Append serde_json::Value TypeScript type (referenced by IpcAgentEvent.arguments
    // but not auto-generated by specta since Value is recursive).
    let value_type = r#"
/** serde_json::Value — required by IpcAgentEvent.arguments */
export type Value = "Null" | { Bool: boolean } | { String: string } | { Number: number } | { Array: Value[] } | { Object: Record<string, Value> };
"#;

    let mut file = std::fs::OpenOptions::new()
        .append(true)
        .open(&bindings_path)
        .expect("open bindings.ts for append");
    file.write_all(value_type.as_bytes())
        .expect("append Value type to bindings.ts");
}

#[test]
fn bindings_contain_expected_commands() {
    let bindings = include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/ui/src/bindings.ts"));
    // Verify the three Phase 9 IPC commands are in the bindings
    assert!(
        bindings.contains("startSession:"),
        "startSession command missing"
    );
    assert!(
        bindings.contains("stopSession:"),
        "stopSession command missing"
    );
    assert!(
        bindings.contains("getSessionStatus:"),
        "getSessionStatus command missing"
    );
    // Verify IpcAgentEvent type is exported
    assert!(
        bindings.contains("IpcAgentEvent"),
        "IpcAgentEvent type missing"
    );
    assert!(
        bindings.contains("SessionStatus"),
        "SessionStatus type missing"
    );
}
